tmax-cloud/hypercloud-api-server

cluster/clusterMemberHandler.go, main.go
클러스터에 초대된 멤버 목록을 조회하기 위한 api 추가하였습니다.
=> [feat] 초대된 cluster 멤버 목록 조회 api 추가

namespace/namespaceHandler.go, namespace/namespaceHub.go, util/caller/K8sApiCaller.go
namespace 생성/변경/삭제 시, 해당 네임스페이스 정보만 알리도록 변경
=> namespace 생성/변경/삭제 시, 해당 네임스페이스 정보만 알리도록 변경

audit/auditHandler.go, namespace/namespaceHandler.go, namespaceClaim/namespaceClaimHandler.go, user/userHandler.go, util/caller/K8sApiCaller.go
[etc] K8sApiCaller.go의 함수가 error를 리턴하도록 리팩토링
해당 함수를 사용하는 코드에서 에러를 처리하도록 변경
=> [etc] K8sApiCaller.go의 함수가 error를 리턴하도록 리팩토링

version/versionHandler.go
=> [mod] 버전 정규식 수정

clusterClaim/clusterClaimHandler.go, util/caller/K8sApiCaller.go
cluster manager 생성 로직을 multi-operator로 옮겼습니다.
=> [mod] cluster manager 생성 로직 삭제

go.mod, go.sum, main.go, util/caller/K8sApiCaller.go
1. ServiceBinding 용 CustomResource List 불러오기 기능 추가
- ClusterTemplate으로 등록된 CR 의 List 조회
- K8s 기본 리소스 중 , Pod를 관리하는 Resource List 조회
=> [feat] ServiceBinding - CustomResource List 불러오기 기능 추가

event/eventHandler.go, main.go, metering/meteringHandler.go, util/caller/K8sApiCaller.go, util/constants.go, util/dataFactory/audit/auditDataFactory.go, util/dataFactory/cluster/clusterDataFactory.go, util/dataFactory/dbConnection.go, util/dataFactory/event/eventDataFactory.go
완료
* k8s event를 watch 하는 로직
* watch한 event를 DB에 저장하는 로직
진행 중
* 저장된 데이터를 조회하는 API
=> [feat] k8s event DB화 기능 추가

util/dataFactory/dbConnection.go
[mod] postgres에서 timescaledb로 DB 변경
=> [mod] postgres에서 timescaledb로 DB 변경

main.go
[etc] string 환경 변수 확인 방식을 strings.EqualFold 함수로 변경
=> [etc] string 환경 변수 확인 방식을 strings.EqualFold 함수로 변경

util/caller/K8sApiCaller.go
https://github.com/tmax-cloud/hypercloud-api-server/pull/16#discussion_r942117024
reviewer 의견 반영하여 로직 수정
=> [etc] GetBindableResources 로직 수정

main.go
- leader election이 예기치 않게 종료됐을 경우, 다시 leader election 로직을 수행하도록 defer func() 추가
- LeaseDuration, RenewDeadline 값을 default 값으로 원복
=> [mod] leader election이 종료가 돼도  다시 실행되도록 수정

.idea/hypercloud-api-server.iml, .idea/misc.xml, .idea/modules.xml, .idea/runConfigurations.xml, .idea/vcs.xml, .idea/workspace.xml, util/caller/K8sApiCaller.go
bindableResource List에 Secret  추가되도록 변경
=> [mod] add Secret resource to bindableResources

util/caller/K8sApiCaller.go
bindableResource List에 secret 추가
=> [mod] add Secret to bindableResources

util/caller/K8sApiCaller.go
[ims][290210] - bindableResource에서 configmap 제거
=> [mod] delete configmap from BindableResources

clusterClaim/clusterClaimHandler.go
[IMS-293625](https://ims.tmaxsoft.com/tody/ims/issue/issueView.do?issueId=293625&menuCode=issue_list)
=> [ims][293625] clusterclaim rejected 상태일 떄 approved로 변경가능하도록 수정

kubectl/kubectlHandler.go, main.go
[feat] GET ~/kubectl 추가하여 이미지,timeout 정보 제공
=> [feat] GET ~/kubectl 추가하여 이미지,timeout 정보 제공

kubectl/kubectlHandler.go, util/caller/K8sApiCaller.go
* GET ~/kubectl이 요청한 유저의 pod의 남은 시간을 반환하도록 수정
* 유저의 아이디에 _를 -로 교체하도록 수정
=> kubectl 기능 관련 오류 수정

util/caller/K8sApiCaller.go
kubectl 컨테이너가 default namespace를 바라보도록 수정
=> [mod] kubectl 컨테이너가 default namespace를 바라보도록 수정

util/caller/K8sApiCaller.go, util/constants.go
kubectl pod에 필요한 configmap을 보안을 위해 pod 생성 후에 삭제
=> [mod] kubectl pod에 필요한 configmap을 보안을 위해 pod 생성 후에 삭제

util/constants.go, util/util.go
[mod] kubectl 이미지가 private registry를 지원하도록 환경변수에 PRIVATE_REGISTRY 추가
=> [mod] kubectl 이미지가 private registry를 지원하도록 환경변수에 PRIVATE_REGISTRY 추가

util/caller/K8sApiCaller.go, util/constants.go
[mod] vim 사용이 가능한 tmaxcloudck kubectl 이미지를 사용하도록 변경
=> [mod] vim 사용이 가능한 tmaxcloudck kubectl 이미지를 사용하도록 변경

util/caller/K8sApiCaller.go, util/constants.go
[ims][300246] kubectl 버전 1.25로 변경 및 label에 자기자신의 이름 추가
=> [ims][300246] kubectl 버전 1.25로 변경 및 label에 자기자신의 이름 추가

main.go, push.sh, util/caller/K8sApiCaller.go, util/util.go
[ims][299887] 런타임 Cert 갱신 기능 추가 및 graceful 종료 로직 추가
=> [ims][299887] 런타임 Cert 갱신 기능 추가 및 graceful 종료 로직 추가
